# Generated by Django 5.0.6 on 2024-06-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='teg',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='post',
            name='image_name',
            field=models.ImageField(upload_to='images'),
        ),
    ]
